version: "3"
services:
  react-app:
    image: react-app
    restart: unless-stopped
    build: ./public/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    restart: unless-stopped
    build: ./server/
    ports:
      - "4000:4000"
    networks:
      - mern-app


networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local